### ISSUE TITLE
Doesnt run

### ISSUE THREAD

**Issue by harsh1412** [gitshinesun/Amazon-Account-Checker-Python#1]
DevTools listening on ws://127.0.0.1:13196/devtools/browser/4d566346-a1f1-41a1-81c4-176ceb041aa9
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\harsh\Desktop\windows\amazon_email_win.py", line 64, in MainProc
    w = driver.find_element_by_id("continue")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"continue"}
  (Session info: headless chrome=72.0.3626.119)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)

**Comment by mosvict** [comment]
hi.
sorry for late reply.
Why do you use python2.7? Please use python3.6.
Thanks.
