### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KANGCOPYRIGHT** [gitshinesun/Amazon-Account-Checker-Python#2]
```
amazon_email_win.py:41: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_options=chrome_options)

DevTools listening on ws://127.0.0.1:52011/devtools/browser/ec068de2-c253-49be-baca-5e94093d00b0
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "Login.py", line 64, in MainProc
    w = driver.find_element_by_id("continue")
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"continue"}
  (Session info: headless chrome=74.0.3729.131)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17763 x86_64)
```

**Comment by mosvict** [comment]
hi.. 
i think you have a problem in python version or chromedriver version..
pls install python 3.6 and run it again.
i will update chromedriver.
